# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171219_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='static/avatar/default.jpg', upload_to='static/avatar/'),
        ),
    ]
