# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171219_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='avatar/default.jpg', upload_to='avatar/'),
        ),
    ]
