# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_sitedetaicategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='siteDetaiCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.SiteDetaiCategory'),
        ),
    ]
