# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171222_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleupdown',
            name='is_down',
            field=models.BooleanField(default=True),
        ),
    ]
